name: healthsync
description: A comprehensive health management app for storing prescriptions, test reports, and managing healthcare documents.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.11.0
  url_launcher: ^6.1.14
  intl: ^0.18.1
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  android_alarm_manager_plus: ^4.0.2
  wakelock_plus: ^1.2.5
  audioplayers: ^6.0.0
  flutter_ringtone_player: ^4.0.0+2
  image_cropper: ^11.0.0
  fl_chart: ^1.1.0
  fuzzy: ^0.5.1
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  http: ^1.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
